services:
  postgres:
    image: postgres:16
    container_name: world-cup-stickers-db
    environment:
      POSTGRES_DB: world_cup_stickers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
